//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffInfo.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class BLOG
    {
        public int BLOG_ID { get; set; }
        public Nullable<int> STAFF_ID { get; set; }
        public string TITLE { get; set; }

        [AllowHtml]
        public string BLOG_BODY { get; set; }
        public string PUBLISHED_DATE { get; set; }
        public string PUBLISHED_BY { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
