//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffInfo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DatabasModel : DbContext
    {
        public DatabasModel()
            : base("name=DatabasModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Job_Title> Job_Title { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Staff_Extensions> Staff_Extensions { get; set; }
        public virtual DbSet<BLOG> BLOGs { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<STAFF_DETAILS_Result> STAFF_DETAILS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STAFF_DETAILS_Result>("STAFF_DETAILS");
        }
    
        public virtual ObjectResult<BRANCHDATA_Result> BRANCHDATA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BRANCHDATA_Result>("BRANCHDATA");
        }
    }
}
