//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Title
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job_Title()
        {
            this.Staffs = new HashSet<Staff>();
        }
    
        public string Job_Title_Code { get; set; }
        public string Position { get; set; }
        public Nullable<decimal> Minimum_Salary { get; set; }
        public Nullable<decimal> Maximum_Salary { get; set; }
        public Nullable<decimal> Actual_Salary { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff> Staffs { get; set; }
    }
}
