//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Extensions
    {
        public int Extension_ID { get; set; }
        public int Staff_ID { get; set; }
        public string Extension_Num { get; set; }
        public string Extension_Num2 { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
